#!/bin/sh

dt=`date +"%Y.%m.%d-%T"`
sda1=`blkid -s UUID -o value /dev/sda1`
sdb1=`blkid -s UUID -o value /dev/sdb1`
sdb2=`blkid -s UUID -o value /dev/sdb2`
sdb3=`blkid -s UUID -o value /dev/sdb3`

echo "Add meg, hogy ez hanyadik mentés legyen, egy jegyű szám legyen (pl: 0)"
read num

if [ ${num} -eq 0 ] 2>/dev/null
then
	echo "Légyszives add meg ismét a számot de két jegyű legyen (pl: 00)"
	read num
else
	num=${dt}
fi

echo "Biztonsági mentés a kernelről"
rsync /boot/initramfs-linux-lts.img /boot/initramfs-linux-lts-snap.img
rsync /boot/vmlinuz-linux-lts /boot/vmlinuz-linux-lts-snap
rsync /boot/intel-ucode.img /boot/intel-ucode-snap.img
sleep 1

echo "Btrfs snapshots a @root, @home, @var subvolume-okról."
btrfs subvolume snapshot / /.snapshots/@root-${num}
btrfs subvolume snapshot /home /.snapshots/@home-${num}
btrfs subvolume snapshot /var /.snapshots/@var-${num}
sleep 1

cat > /.snapshots/@root-${num}/etc/fstab << EOF
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>

# /dev/sdb2 UUID=2ac81381-1225-4194-a1fe-8c48c22af682
UUID=${sdb3}	/         	btrfs     	rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,subvol=/@snapshots/@root-${num},subvol=@snapshots/@root-${num}	0 0

# /dev/sdb1
UUID=${sdb1}	/boot     	vfat      	rw,noatime,discard,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2

# /dev/sdb2
UUID=${sdb3}	/home     	btrfs     	rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,subvol=/@snapshots/@home-${num},subvol=@snapshots/@home-${num}	0 0

# /dev/sdb2
UUID=${sdb3}	/var		btrfs  	 	rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,subvol=/@snapshots/@var-${num},subvol=@snapshots/@var-${num}	0 0

# /dev/sdb2
UUID=${sdb3}	/.snapshots	btrfs     	rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,subvol=/@snapshots,subvol=@snapshots	0 0

# /dev/sda1
UUID=${sda1}	/mnt/sda	ext4		defaults,noatime,discard	0 2

# /dev/sdb2
UUID=${sdb2}	none		swap		defaults	0 0
EOF

sleep 1
echo "GRUB frissítése"
grub-mkconfig -o /boot/grub/grub.cfg

sleep 1
echo "Mentés elkészült!"
