theme = "modern"
icons = "awesome5"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"
# notifier = "swaynag"

[[notify]]
format = "{state}"

# [[block]]
# block = "battery"
# interval = 10
# format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "battery"
#driver = "upower"
format = "{percentage} {time}"
#full_format = "{percentage} {time}"
[block.theme_overrides]
good_bg = "#0088CC"
good_fg = "#ffffff"


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
icons_format = "{icon}"

[[block]]
block = "cpu"
icons_format = "{icon}"
interval = 1
#[icons_overrides]
#cpu = " | | "

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "pacman"
# interval = 60
# #format = "{pacman} updates available"
# format = "{pacman} + {aur} = {both} updates available"
# format_singular = "{both} update available"
# format_up_to_date = "system up to date"
# critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command = "pikaur -Qua"
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
#on_click = "fakeroot pakaur -Qu --dbpath /tmp/checkup-db-volo/ | rofi --show dmenu"

[[block]]
block = "networkmanager"
on_click = "kitty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = ["enp59s0", "wlp0s20f3"]
interface_name_include = []
#ap_format = "{ssid^10}"
ap_format = "{ssid^0}"
icons_format = "{icon}"
[block.theme_overrides]
good_bg = "#0088CC"
good_fg = "#ffffff"

[[block]]
block = "sound"
#headphones_indicator = ""
on_click = "pavucontrol"
#icons_format = "{icon}"

[[block]]
block = "time"
format = "%a %m/%d %R"
#icons_format = "{icon}"
on_click = "~/.config/i3/script/calendar.py"
timezone = "Europe/Budapest"
interval = 5
locale = "hu_HU"

